name: project CI workflow
run-name: ${{ github.actor }} is running CI pipeline
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Build Job is triggered by ${{ github.event_name }} event."
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - name: List files in the repository
        run: |
          ls -R
      - name: Grant permissions to gradle
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew build
      - run: echo "The workflow is ready to test repository's code"
      - run: echo "This job's status is ${{ job.status }}"
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - run: echo "Running test job"
      - name: Test project
        run: ./gradlew test