name: project CI workflow
run-name: ${{ github.actor }} is running CI pipeline
on: [push]
jobs:
  info-job:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Job is triggered by ${{ github.event_name }} event."
      - run: echo "The job is running on ${{ runner.os }} os"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "The workflow is ready to test repository's code"
      - run: echo "This job's status is ${{ job.status }}"