name: project CI workflow
run-name: ${{ github.actor }} is running CI pipeline
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Build Job is triggered by ${{ github.event_name }} event."
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Grant permissions to gradle
        run: chmod +x gradlew
      - name: Build and test project
        run: ./gradlew test
      - name: Generate Jacoco report
        run: ./gradlew jacocoTestReport
      - name: Generate Allure report
        run: ./gradlew allureReport
      - name: Store reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/
      - run: echo "The workflow is ready to test repository's code"
      - run: echo "This job's status is ${{ job.status }}"